import re

REF_NAMETEMPLATE = '%'
REF_PATHTEMPLATE = '@'
MATCH_PATTERN = re.compile('{([%s%s])?(\w+)}' % (REF_PATHTEMPLATE, REF_NAMETEMPLATE))

ENV_VAR = 'TEMPLATERESOLVER_CONFIG'

KEY_NAMETEMPLATE = 'names'
KEY_PATHTEMPLATE = 'templates'
KEY_TOKEN = 'tokens'
TOKEN_TYPE = 'type'

WILDCARD = '*'
WILDCARD_ONE = '?'
